#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

n=0
until [ $n == 10 ]
do
        if [ $n == 8 ]
        then
                echo "Best School"
                echo "Hi"
                n=$((n+1))
                continue
        fi
        echo "Best School"
        n=$((n+1))
done
