#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration
n=0
for n in {1..20}
do
        if [ $n == 4 ]
        then    echo $n
                echo "bad luck from china"
        elif [ $n == 9 ]
        then
                echo $n
                echo "bad luck from japan"
        elif [ $n == 17 ]
        then
                echo $n
                echo "bad luck from italy"
        else
                echo $n
        fi
        n=$((n+1))
done
