#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

for hour in {0..12}
do
        echo "Hour: $hour"
        for minute in {1..59}
        do
                echo $minute
        done
done
